// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_flower1Completed = new UnifiedAchievement("Flower1Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower1"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQAA"
#else
            "Flower1Completed"
#endif
            );

        public static UnifiedAchievement Flower1Completed
        {
            get { return s_flower1Completed; }
        }

        private static readonly UnifiedAchievement s_flower2Completed = new UnifiedAchievement("Flower2Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower2"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQBQ"
#else
            "Flower2Completed"
#endif
            );

        public static UnifiedAchievement Flower2Completed
        {
            get { return s_flower2Completed; }
        }

        private static readonly UnifiedAchievement s_flower3Completed = new UnifiedAchievement("Flower3Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower3"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQBg"
#else
            "Flower3Completed"
#endif
            );

        public static UnifiedAchievement Flower3Completed
        {
            get { return s_flower3Completed; }
        }

        private static readonly UnifiedAchievement s_flower4Completed = new UnifiedAchievement("Flower4Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower4"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQBw"
#else
            "Flower4Completed"
#endif
            );

        public static UnifiedAchievement Flower4Completed
        {
            get { return s_flower4Completed; }
        }

        private static readonly UnifiedAchievement s_flower5Completed = new UnifiedAchievement("Flower5Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower5"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQCA"
#else
            "Flower5Completed"
#endif
            );

        public static UnifiedAchievement Flower5Completed
        {
            get { return s_flower5Completed; }
        }

        private static readonly UnifiedAchievement s_flower6Completed = new UnifiedAchievement("Flower6Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower6"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQCQ"
#else
            "Flower6Completed"
#endif
            );

        public static UnifiedAchievement Flower6Completed
        {
            get { return s_flower6Completed; }
        }

        private static readonly UnifiedAchievement s_flower7Completed = new UnifiedAchievement("Flower7Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower7"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQCg"
#else
            "Flower7Completed"
#endif
            );

        public static UnifiedAchievement Flower7Completed
        {
            get { return s_flower7Completed; }
        }

        private static readonly UnifiedAchievement s_flower8Completed = new UnifiedAchievement("Flower8Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower8"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQCw"
#else
            "Flower8Completed"
#endif
            );

        public static UnifiedAchievement Flower8Completed
        {
            get { return s_flower8Completed; }
        }

        private static readonly UnifiedAchievement s_flower9Completed = new UnifiedAchievement("Flower9Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower9"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQDA"
#else
            "Flower9Completed"
#endif
            );

        public static UnifiedAchievement Flower9Completed
        {
            get { return s_flower9Completed; }
        }

        private static readonly UnifiedAchievement s_flower10Completed = new UnifiedAchievement("Flower10Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower10"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQDQ"
#else
            "Flower10Completed"
#endif
            );

        public static UnifiedAchievement Flower10Completed
        {
            get { return s_flower10Completed; }
        }

        private static readonly UnifiedAchievement s_flower11Completed = new UnifiedAchievement("Flower11Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower11"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQDg"
#else
            "Flower11Completed"
#endif
            );

        public static UnifiedAchievement Flower11Completed
        {
            get { return s_flower11Completed; }
        }

        private static readonly UnifiedAchievement s_flower12Completed = new UnifiedAchievement("Flower12Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower12"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQDw"
#else
            "Flower12Completed"
#endif
            );

        public static UnifiedAchievement Flower12Completed
        {
            get { return s_flower12Completed; }
        }

        private static readonly UnifiedAchievement s_flower13Completed = new UnifiedAchievement("Flower13Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower13"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQEA"
#else
            "Flower13Completed"
#endif
            );

        public static UnifiedAchievement Flower13Completed
        {
            get { return s_flower13Completed; }
        }

        private static readonly UnifiedAchievement s_flower14Completed = new UnifiedAchievement("Flower14Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower14"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQEQ"
#else
            "Flower14Completed"
#endif
            );

        public static UnifiedAchievement Flower14Completed
        {
            get { return s_flower14Completed; }
        }

        private static readonly UnifiedAchievement s_flower15Completed = new UnifiedAchievement("Flower15Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower15"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQEg"
#else
            "Flower15Completed"
#endif
            );

        public static UnifiedAchievement Flower15Completed
        {
            get { return s_flower15Completed; }
        }

        private static readonly UnifiedAchievement s_flower16Completed = new UnifiedAchievement("Flower16Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower16"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQEw"
#else
            "Flower16Completed"
#endif
            );

        public static UnifiedAchievement Flower16Completed
        {
            get { return s_flower16Completed; }
        }

        private static readonly UnifiedAchievement s_flower17Completed = new UnifiedAchievement("Flower17Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower17"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQFA"
#else
            "Flower17Completed"
#endif
            );

        public static UnifiedAchievement Flower17Completed
        {
            get { return s_flower17Completed; }
        }

        private static readonly UnifiedAchievement s_flower18Completed = new UnifiedAchievement("Flower18Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower18"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQFQ"
#else
            "Flower18Completed"
#endif
            );

        public static UnifiedAchievement Flower18Completed
        {
            get { return s_flower18Completed; }
        }

        private static readonly UnifiedAchievement s_flower19Completed = new UnifiedAchievement("Flower19Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower19"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQFg"
#else
            "Flower19Completed"
#endif
            );

        public static UnifiedAchievement Flower19Completed
        {
            get { return s_flower19Completed; }
        }

        private static readonly UnifiedAchievement s_flower20Completed = new UnifiedAchievement("Flower20Completed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.BombChomp.PocketMazes.Flower20"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIgI-V1NgTEAIQFw"
#else
            "Flower20Completed"
#endif
            );

        public static UnifiedAchievement Flower20Completed
        {
            get { return s_flower20Completed; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_flower1Completed,
            s_flower2Completed,
            s_flower3Completed,
            s_flower4Completed,
            s_flower5Completed,
            s_flower6Completed,
            s_flower7Completed,
            s_flower8Completed,
            s_flower9Completed,
            s_flower10Completed,
            s_flower11Completed,
            s_flower12Completed,
            s_flower13Completed,
            s_flower14Completed,
            s_flower15Completed,
            s_flower16Completed,
            s_flower17Completed,
            s_flower18Completed,
            s_flower19Completed,
            s_flower20Completed,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "Flower1Completed", s_flower1Completed },
            { "Flower2Completed", s_flower2Completed },
            { "Flower3Completed", s_flower3Completed },
            { "Flower4Completed", s_flower4Completed },
            { "Flower5Completed", s_flower5Completed },
            { "Flower6Completed", s_flower6Completed },
            { "Flower7Completed", s_flower7Completed },
            { "Flower8Completed", s_flower8Completed },
            { "Flower9Completed", s_flower9Completed },
            { "Flower10Completed", s_flower10Completed },
            { "Flower11Completed", s_flower11Completed },
            { "Flower12Completed", s_flower12Completed },
            { "Flower13Completed", s_flower13Completed },
            { "Flower14Completed", s_flower14Completed },
            { "Flower15Completed", s_flower15Completed },
            { "Flower16Completed", s_flower16Completed },
            { "Flower17Completed", s_flower17Completed },
            { "Flower18Completed", s_flower18Completed },
            { "Flower19Completed", s_flower19Completed },
            { "Flower20Completed", s_flower20Completed },
        };
    }
}
