// <copyright file="CloudIDs.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
#if (UNITY_ANDROID || UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
    using Internal;
    using UnityEngine;
#endif
    /// <summary>
    /// Provides access to achievement- and leaderboard IDs registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudIDs
    {
        /// <summary>
        /// Contains properties that retrieves achievement IDs for the current platform.
        /// </summary>
        public static class AchievementIDs
        {
            public static string Flower1Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQAA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower1";
#elif UNITY_EDITOR
                    return "Flower1Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower2Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQBQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower2";
#elif UNITY_EDITOR
                    return "Flower2Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower3Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQBg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower3";
#elif UNITY_EDITOR
                    return "Flower3Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower4Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQBw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower4";
#elif UNITY_EDITOR
                    return "Flower4Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower5Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQCA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower5";
#elif UNITY_EDITOR
                    return "Flower5Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower6Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQCQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower6";
#elif UNITY_EDITOR
                    return "Flower6Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower7Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQCg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower7";
#elif UNITY_EDITOR
                    return "Flower7Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower8Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQCw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower8";
#elif UNITY_EDITOR
                    return "Flower8Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower9Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQDA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower9";
#elif UNITY_EDITOR
                    return "Flower9Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower10Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQDQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower10";
#elif UNITY_EDITOR
                    return "Flower10Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower11Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQDg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower11";
#elif UNITY_EDITOR
                    return "Flower11Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower12Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQDw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower12";
#elif UNITY_EDITOR
                    return "Flower12Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower13Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQEA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower13";
#elif UNITY_EDITOR
                    return "Flower13Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower14Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQEQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower14";
#elif UNITY_EDITOR
                    return "Flower14Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower15Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQEg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower15";
#elif UNITY_EDITOR
                    return "Flower15Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower16Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQEw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower16";
#elif UNITY_EDITOR
                    return "Flower16Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower17Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQFA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower17";
#elif UNITY_EDITOR
                    return "Flower17Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower18Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQFQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower18";
#elif UNITY_EDITOR
                    return "Flower18Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower19Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQFg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower19";
#elif UNITY_EDITOR
                    return "Flower19Completed";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Flower20Completed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQFw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.BombChomp.PocketMazes.Flower20";
#elif UNITY_EDITOR
                    return "Flower20Completed";
#else
                    return string.Empty;
#endif
                }
            }
        }

        /// <summary>
        /// Contains properties that retrieves leaderboard IDs for the current platform.
        /// </summary>
        public static class LeaderboardIDs
        {
            public static string PuzzlesSolved
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIgI-V1NgTEAIQGw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "puzzles.001";
#elif UNITY_EDITOR
                    return "PuzzlesSolved";
#else
                    return string.Empty;
#endif
                }
            }
        }
    }
}
